spring.application.name=Product Service
#logging.level.org.springframework.web=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productservice
spring.datasource.username=vashali
#spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#for local not needed
spring.data.redis.host=localhost
spring.data.redis.port=6379

#"Should this application register itself with a Eureka server?"-> true
eureka.client.registerWithEureka= true
#"Should this application fetch the registry (list of services) from Eureka?"-> true
eureka.client.fetchRegistry= true
#since the eureka is not running on default port hence need to mention the eureka path
#eureka.client.service-url.defaultZone=http://localhost:8282/eureka

#to run product service on multiple servers - without hardcoding
server.port= ${PRODUCTSERVICE_PORT}
